language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip pipenv
  - pipenv lock --requirements > requirements.txt
  - pipenv lock --dev --requirements > test_requirements.txt
install:
  - pip install -U -r requirements.txt
  - pip install -U -r test_requirements.txt
script:
  - mypy --ignore-missing-imports --follow-imports=skip --disallow-untyped-defs --strict-optional --warn-no-return .
  - pytest -v
